### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by dynamitemedia** [de-luxe/burstcoin-faucet#9]
this is more or a question...  do we need any certain webserver for this?

and could we set it up to redirect after claiming to maybe play a game?

**Comment by de-luxe** [comment]
the faucet is a executable jar file with included tomcat server ... (will not work with kind of php webhosting)
to redirect after claim, the code has to be changed at https://github.com/de-luxe/burstcoin-faucet/blob/master/src/main/java/burstcoin/faucet/controller/FaucetController.java#L248
basically it redirects to itself with a message parameter currently.

**Comment by dynamitemedia** [comment]
thank you,  can i redirect to php hosted site tho?  sorry for my confusion...

normally upload files etc to a server lol

**Comment by de-luxe** [comment]
nope sry do not know a php faucet.
this faucet was made for burstcoin, so the same technology as the core wallet was used ... as a running wallet is needed to send coins anyway, i expected the faucet to be run on same server/environment.

**Comment by dynamitemedia** [comment]
thanks so sorry for another question and if this is already posted some where im sorry and you can point me right direction but i should run this locally so that it takes from my wallet then?   do you have a install guide? i may have missed it

**Comment by de-luxe** [comment]
for running on localhost, you only need to specify wallet and pass of faucet account in faucet.properties https://github.com/de-luxe/burstcoin-faucet/blob/master/faucet.default.properties
for running on another domain you will need to get google recaptcha keys
just execute run.bat/exe or included command

More info/support:
https://forums.burst-team.us/topic/215
